sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t docker-react .

script:
  - docker run docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-eu-central-1-352905010987
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key:
    secure: $AWS_SECRET
