# Bulding the react app

FROM mhart/alpine-node AS build

WORKDIR /usr/app

COPY package*.json ./

RUN npm i

COPY ./ ./

RUN npm run build

# Installing NGINX and copying over
# the build folder generated by building the react app

FROM nginx

EXPOSE 80

COPY --from=build /usr/app/build /usr/share/nginx/html